memory_limit = 128M
upload_max_filesize = 2M
post_max_size = 8M
max_execution_time = 30
default_charset = "UTF-8"
date.timezone = "Europe/London"
session.save_path = "/var/lib/php/session"
opcache.memory_consumption = 128
opcache.max_accelerated_files = 4000
file_uploads = On
display_errors = Off
error_reporting = 24567
output_buffering = 4096
max_file_uploads = 20
max_input_vars = 1000
session.auto_start = Off
session.gc_maxlifetime = 1440
session.cookie_path = "/"
session.name = "PHPSESSID"
